- name: Install DHCP Client Package
  package:
    name:
      - dhcpcd
    state: latest

- name: Get IP Address Through DHCP
  ansible.builtin.command: dhcpcd

- name: Remove Statically assigned IP from Docker
  ansible.builtin.command: ip a d "{{ ansible_facts['all_ipv4_addresses'] | first }}" dev eth0
