- name: Install DHCP Server package
  package:
    name:
      - dhcp
    state: latest

- name: Create DHCP Lease file
  ansible.builtin.file:
    path: /var/lib/dhcp/dhcpd.leases
    mode: '0755'
    state: touch

- name: Copy Config File
  template:
    src: "dhcpd.j2"
    dest: /etc/dhcp/dhcpd.conf
    mode: '0755'

- name: Start DHCP Service
  ansible.builtin.service:
    name: dhcpd
    state: started
