- name: Install DHCP server package
  package:
    name:
      - dhcp
    state: latest

- name: Create lease file
  ansible.builtin.file:
    path: /var/lib/dhcp/dhcpd.leases
    state: touch

- name: generate config file from a template
  template:
    src: "dhcpd.j2"
    dest: /etc/dhcp/dhcpd.conf

- name: Start DHCP service
  ansible.builtin.service:
    name: dhcpd
    state: started