---

- hosts: all
  pre_tasks: # This task should be run before any other PLAY
    - name: Install updates
      tags: always
      package:
        update_cache: true
      changed_when: false
      
- hosts: containers # In our case containers = all, as defined in inventory
  roles:
    - containers
  
- hosts: all
  roles:
    - base
  

- hosts: workstations
  roles:
    - workstations