general:
  random_seed: 10
  default_container_image_name: base_image

networks:
  internal_net:
    num_containers: 4
    network_addr: "{{ general.random_seed | generate_ipv4_address(True) }}"
    gateway_addr: "{{ general.random_seed | generate_ipv4_address(True) }}"
    machines:
      - name: internal_pc_1
      - name: internal_pc_2
      - name: internal_pc_3

  dmz_net:
    num_containers: 4
    network_addr: "{{ general.random_seed | generate_ipv4_address(True) }}"
    gateway_addr: "{{ general.random_seed | generate_ipv4_address(True) }}"
    machines:
      - name: internal_pc_1
      - name: internal_pc_2
      - name: internal_pc_3

  external_net:
    num_containers: 4
    network_addr: "{{ general.random_seed | generate_ipv4_address(True) }}"
    gateway_addr: "{{ general.random_seed | generate_ipv4_address(True) }}"
    machines:
      - name: internal_pc_1
      - name: internal_pc_2
      - name: internal_pc_3
