- name: Create Container
  community.general.docker_container:
    name: "{{ pc_name }}"
    image: "{{ default_container_image }}"
    state: started

- name: Add the container to inventory
  ansible.builtin.add_host:
    name: "{{ pc_name }}"
    ansible_connection: docker
    groups: internal_net

- name: Add a container to Network
  docker_network:
    name: "{{ internal_network_name }}"
    ipam_config:
      - subnet: 172.3.27.0/24 # Hard-coded
        gateway: 172.3.27.2 # Hard-coded
    connected:
      - "{{ pc_name }}"
    appends: yes

- debug: var=test_variable