- name: Create Container
  community.general.docker_container:
    name: "{{ pc_info.name }}"
    image: "{{ general.default_container_image_name }}"
    networks: "{{ pc_info.networks }}"
    state: started

- name: Add the container to inventory
  ansible.builtin.add_host:
    name: "{{ pc_info.name }}"
    ansible_connection: docker
    groups: "{{ pc_info.group }}"
