- name: Create Container
  community.general.docker_container:
    name: "{{ pc_name }}"
    image: "{{ general.default_container_image_name }}"
    state: started

- name: Add the container to inventory
  ansible.builtin.add_host:
    name: "{{ pc_name }}"
    ansible_connection: docker
    groups: "{{ network_name }}"

- name: Add a container to Network
  community.docker.docker_network:
    name: "{{ network_name }}"
    ipam_config:
      - subnet: "{{ network_addr }}"
        gateway: "{{ gateway_addr }}"
    connected:
      - "{{ pc_name }}"
    appends: true
