- name: Start Docker Service
  ansible.builtin.sysvinit:
    name: docker
    state: started
    enabled: true

- name: Build Image
  community.docker.docker_image:
    name: "{{ general.default_container_image_name }}"
    build:
      path: .
    state: present
    source: build

- name: Create Networks
  community.docker.docker_network:
    name: "{{ item }}"
    ipam_config:
      - subnet: "{{ networks[item].network_addr }}"
        gateway: "{{ networks[item].gateway_addr }}"
  loop: "{{ networks.keys() }}"

- name: Container Operations
  ansible.builtin.include_tasks: containers.yml
  loop: "{{ machines }}"
  loop_control:
    loop_var: pc_info

# - name: Container Operations (DMZ Network)
#   ansible.builtin.include_tasks: containers.yml
#   vars:
#     network_name: dmz_net
#   loop: "{{ networks.dmz_net.machines }}"
#   loop_control:
#     loop_var: pc_info

# - name: Container Operations (External Network)
#   ansible.builtin.include_tasks: containers.yml
#   vars:
#     network_name: external_net
#   loop: "{{ networks.external_net.machines }}"
#   loop_control:
#     loop_var: pc_info
