- name: Start Docker Service
  ansible.builtin.sysvinit:
    name: docker
    state: started
    enabled: true

# - name: Show all the hosts in the inventory
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop: "{{ groups['all'] }}"

- name: Build Image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    build:
      path: .
    state: present
    source: build

- name: Create Docker network
  docker_network:
    name: "{{ internal_network_name }}"

- name: Container Operations
  ansible.builtin.include_tasks: containers.yml
  loop: "{{ internal_network_pc_names }}"
  loop_control:
    loop_var: pc_name
