- name: Start Docker Service
  ansible.builtin.sysvinit:
    name: docker
    state: started
    enabled: true

- name: Building Images
  community.docker.docker_image:
    name: "{{ image.name }}"
    build:
      path: "{{ image.path }}"
      dockerfile: "{{ image.dockerfile | default('Dockerfile') }}"
    state: present
    source: build
  loop: "{{ general.images }}"
  loop_control:
    loop_var: image

- name: Create Docker Networks
  community.docker.docker_network:
    name: "{{ item }}"
    ipam_config:
      - subnet: "{{ networks[item].network_addr }}"
        gateway: "{{ networks[item].gateway_addr }}"
  loop: "{{ networks.keys() }}"

- name: Container Operation Tasks
  ansible.builtin.include_tasks: containers.yml
  loop: "{{ machines }}"
  loop_control:
    loop_var: pc_info
