- name: Start Docker Service
  ansible.builtin.sysvinit:
    name: docker
    state: started
    enabled: true

- name: Build Image
  community.docker.docker_image:
    name: "{{ general.default_container_image_name }}"
    build:
      path: .
    state: present
    source: build

- name: Create Networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop: "{{ networks.keys() }}"

# - name: Display users
#   debug:
#     msg: "{{ item }}"
#   loop: "{{ networks.internal_net.machines }}"

- name: Container Operations
  ansible.builtin.include_tasks: containers.yml
  vars:
    network_name: internal_net
  loop: "{{ networks.internal_net.machines | map(attribute='name') }}"
  loop_control:
    loop_var: pc_name
