- name: Default Policy for FORWARD Chain is DROP
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP

- name: Accept Already Established Connections to Internal Network
  ansible.builtin.iptables:
    chain: FORWARD
    ctstate: ESTABLISHED,RELATED
    destination: "{{ networks.internal_net.network_addr }}"
    jump: ACCEPT

- name: Accept Connections From Internal Network [1]
  ansible.builtin.iptables:
    chain: FORWARD
    ctstate: NEW,ESTABLISHED,RELATED
    source: "{{ networks.internal_net.network_addr }}"
    jump: ACCEPT

