- name: Iptables Flush FILTER Table
  ansible.builtin.iptables:
    table: filter
    flush: true

- name: Configure NAT
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ networks.internal_net.network_addr }},{{ networks.dmz_net.network_addr }}"
    jump: MASQUERADE

- name: Configure Static Route
  ansible.builtin.command: ip r add {{ networks.internal_net.network_addr }} via {{ ((machines | selectattr('name', '==', 'internal_router'))[0]['networks'] | selectattr('name', '==', 'dmz_net') | map(attribute='ipv4_address')) | first }}
