- name: Iptables Flush NAT Table
  ansible.builtin.iptables:
    table: nat
    flush: true

- name: Internal Router Tasks
  ansible.builtin.include_tasks: internal_router.yml
  when: not is_edge_router

- name: Edge Router Tasks
  ansible.builtin.include_tasks: edge_router.yml
  when: is_edge_router
