# Playbook used to setup containers.

---
- name: Base Tasks
  hosts: localhost
  roles:
    - base

- name: DHCP Servers Tasks
  hosts: dhcp_servers
  roles:
    - dhcp

- name: Internal Network Tasks
  hosts: pcs
  roles:
    - internal

- name: DNS Servers Tasks
  hosts: dns_servers
  roles:
    - dns

- name: Router Tasks
  hosts: routers
  roles:
    - routers
