# Playbook used to setup containers.

---
- name: Base Tasks
  hosts: localhost
  roles:
    - base

- name: DHCP Server
  hosts: dhcp
  roles:
    - dhcp

- name: Internal Network Tasks
  hosts: pcs
  roles:
    - internal


# - name: Router Tasks
#   hosts: routers
#   roles:
#     - routers
