# Playbook used to setup containers.

---

# Common Network Setup

- hosts: localhost
  pre_tasks:
    - name: Remove Stale Containers
      ansible.builtin.include_tasks: teardown.yml
      loop: "{{ machines + vulnerables.machines }}"
      loop_control:
        loop_var: pc_info

- name: Base Tasks
  hosts: localhost
  roles:
    - base

- name: DHCP Servers Tasks
  hosts: dhcp_servers
  roles:
    - dhcp

- name: Internal Network PCs Tasks
  hosts: pcs
  roles:
    - internal_pcs

- name: Internal Network Tasks
  hosts: internal
  roles:
    - internal

- name: DNS Servers Tasks
  hosts: dns_servers
  roles:
    - dns

- name: Router Tasks
  hosts: routers
  roles:
    - routers

- name: Firewall Tasks
  hosts: firewalls
  roles:
    - firewalls

- name: External Tasks
  hosts: external
  roles:
    - external

# Scenario

- name: Vulnerable Machine Launch
  hosts: localhost
  roles:
    - custom_machines

- name: DMZ Network Tasks
  hosts: dmz
  roles:
    - dmz

- name: Entrypoint Tasks
  hosts: scenario
  roles:
    - entrypoint

- name: Reverse Proxy Tasks
  hosts: reverse_proxies
  vars: 
    machine_vars: "{{ (vulnerables.machines | selectattr('name', '==', inventory_hostname))[0]['vars'] }}"
  roles:
    - reverse_proxies
