# Playbook used to setup containers.

---

# - hosts: localhost
#   tasks:
#   - debug:
#       msg: "{{ (setup.machines | selectattr('name', '==', 'attacker_machine'))[0]['setup'] }}"
#   - debug: var="{{ setup.machines | selectattr('name', '==', ansible_hostname) | list | length == 1 }}"

- hosts: localhost
  tasks:
    - name: Remove Stale Containers
      ansible.builtin.include_tasks: teardown.yml
      loop: "{{ machines + vulnerables.machines }}"
      loop_control:
        loop_var: pc_info

- name: Base Tasks
  hosts: localhost
  roles:
    - base

- name: DHCP Servers Tasks
  hosts: dhcp_servers
  roles:
    - dhcp

- name: Internal Network PCs Tasks
  hosts: pcs
  roles:
    - internal_pcs

- name: Internal Network Tasks
  hosts: internal
  roles:
    - internal

- name: DNS Servers Tasks
  hosts: dns_servers
  roles:
    - dns

- name: DMZ Network Tasks
  hosts: dmz
  roles:
    - dmz

- name: Router Tasks
  hosts: routers
  roles:
    - routers

- name: Firewall Tasks
  hosts: firewalls
  roles:
    - firewalls

- name: External Tasks
  hosts: external
  roles:
    - external

- name: Vulnerable Machine Launch
  hosts: localhost
  roles:
    - vuln_machines_deploy

- name: Vulnerable Machine Tasks
  hosts: vuln_machines
  roles:
    - vuln_machines_tasks

- name: Entrypoint Tasks
  hosts: scenario
  roles:
    - entrypoint