# Playbook used to setup containers.

---
- hosts: localhost
  tasks:
    - name: Remove Stale Containers
      ansible.builtin.include_tasks: teardown.yml
      loop: "{{ machines }}"
      loop_control:
        loop_var: pc_info

- name: Base Tasks
  hosts: localhost
  roles:
    - base

- name: DHCP Servers Tasks
  hosts: dhcp_servers
  roles:
    - dhcp

- name: Internal Network PCs Tasks
  hosts: pcs
  roles:
    - internal_pcs

- name: Internal Network Tasks
  hosts: internal
  roles:
    - internal

- name: DNS Servers Tasks
  hosts: dns_servers
  roles:
    - dns

- name: DMZ Network Tasks
  hosts: dmz
  roles:
    - dmz

- name: Router Tasks
  hosts: routers
  roles:
    - routers

- name: Firewall Tasks
  hosts: firewalls
  roles:
    - firewalls

- name: External Tasks
  hosts: external
  roles:
    - external