general:
  default_container_image_name: base_image
  random_byte: "{{ 254 | random(start=30, seed=11) }}"

networks:
  internal_net:
    network_addr: 172.{{ general.random_byte }}.0.0/24
    gateway_addr: 172.{{ general.random_byte }}.0.254      

  dmz_net:
    network_addr: 172.{{ general.random_byte | int - 5 }}.0.0/24
    gateway_addr: 172.{{ general.random_byte | int - 5 }}.0.254      

  external_net:
    network_addr: 172.{{ general.random_byte | int - 10 }}.0.0/24
    gateway_addr: 172.{{ general.random_byte | int - 10 }}.0.254

machines:
  - name: dhcp_server
    group: dhcp_servers
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.3
    
  - name: internal_pc_1
    group: pcs
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.2

  - name: router_1
    group: routers
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.10
      - name: dmz_net
        ipv4_address: 172.{{ general.random_byte | int - 5 }}.0.1

  - name: dns_server
    group: dns_servers
    exposed_ports:
      - 53/tcp
      - 53/udp
      - 953
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.20

  - name: web_server
    group: web_servers
    networks:
      - name: dmz_net
        ipv4_address: 172.{{ general.random_byte | int - 5 }}.0.5

  # - name: external_pc_1
  #   group: pcs
  #   networks:
  #     - name: external_net
  #       ipv4_address: 172.{{ general.random_byte | int - 10 }}.0.2
