general:
  default_container_image_name: base_image
  attacker_container_image_name: kali_test_img
  random_byte: "{{ 254 | random(start=30, seed=11) }}"

networks:
  internal_net:
    network_addr: 172.{{ general.random_byte }}.0.0/24
    gateway_addr: 172.{{ general.random_byte }}.0.254      

  dmz_net:
    network_addr: 172.{{ general.random_byte | int - 5 }}.0.0/24
    gateway_addr: 172.{{ general.random_byte | int - 5 }}.0.254      

  external_net:
    network_addr: 172.{{ general.random_byte | int - 10 }}.0.0/24
    gateway_addr: 172.{{ general.random_byte | int - 10 }}.0.254

machines:
  - name: dhcp_server
    group: 
      - dhcp_servers
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.3
    
  - name: internal_pc_1
    group: 
      - pcs
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.2

  - name: internal_router
    group: 
      - routers
      - firewalls
    dns_server: true
    networks:
      - name: internal_net
        ipv4_address: 172.{{ general.random_byte }}.0.1
      - name: dmz_net
        ipv4_address: 172.{{ general.random_byte | int - 5 }}.0.1

  - name: edge_router
    group: 
      - routers
    dns_server: true
    networks:
      - name: dmz_net
        ipv4_address: 172.{{ general.random_byte | int - 5 }}.0.2
      - name: external_net
        ipv4_address: 172.{{ general.random_byte | int - 10 }}.0.1

  - name: dns_server
    group: 
      - dns_servers
    exposed_ports:
      - 53/tcp
      - 53/udp
      - 953
    networks:
      - name: dmz_net
        ipv4_address: 172.{{ general.random_byte | int - 5 }}.0.20

  - name: attacker_machine
    image: kali_test_img
    group:
      - external
    published_ports:
      - 5900:5900
      - 6080:6080
    dns_server: true
    networks:
      - name: external_net
        ipv4_address: 172.{{ general.random_byte | int - 10 }}.0.2

vulnerables:
  general:
    images: 
      - name: unifi_log4j
        scenario: log4j
        dockerfile: Dockerfile.alpine.mongo
        args:
          VERSION: "6.4.54"
        credentials:
          username: test_user
          password: test_password
          email: admin@hotmail.com

  machines:
    - name: vuln_service
      image: unifi_log4j
      group: 
        - vuln_machines
      dns_server: true
      networks:
        - name: dmz_net
          ipv4_address: 172.{{ general.random_byte | int - 5 }}.0.30
      volumes:
        - "{{ playbook_dir }}/scenarios/log4j/unifi-certs:/usr/lib/unifi/cert"
  
setup:
  machines:
    - name: attacker_machine
      setup: "{{ playbook_dir }}/scenarios/log4j/setup/*.j2"
