- name: Install DHCP client package
  package:
    name:
      - dhcpcd
    state: latest

- name: Get IP Address
  ansible.builtin.command: dhcpcd

- name: Remove Statically assigned IP from Docker
  ansible.builtin.command: ip a d "{{ ansible_facts['all_ipv4_addresses'] | first }}" dev eth0

- name: Remove Default Route
  ansible.builtin.command: ip r del default

- name: Add New Default Route
  ansible.builtin.command: "ip r add default via 
    {{ ((machines | selectattr('name', '==', 'router_1'))[0]['networks'] | 
    selectattr('name', '==', 'internal_net') | map(attribute='ipv4_address')) | first }}"
