apache_package_name: apache2
apache_service: apache2
nano_package_name: nano
sudo_package_name: sudo
ssh_users: "root simone"
ssh_template_file: sshd_config_alpine.j2

# Name of this file can be either the IP address of the target or the corresponding DNS name.