- name: Install apache and nano package
  tags: apache,nano
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ nano_package_name }}"
      - "{{ sudo_package_name }}"
    state: latest
  
- name: Start apache2
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_eth0.ipv4.address == "172.17.0.2"

- name: Change email address for admin
  tags: apache
  lineinfile:
    path: /etc/apache2/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin me@here.ps
  when: ansible_eth0.ipv4.address == "172.17.0.2"
  notify: restart_apache # Using handlers

- name: Copy file to machine
  tags: copy
  copy:
    src: index.html
    dest: /var/www/localhost/htdocs/index.html
    owner: root
    group: root
    mode: 0644