- name: Internal Firewall Tasks
  ansible.builtin.include_tasks: internal/internal_firewall.yml
  when: not is_edge_router

- name: External Firewall Tasks
  vars:
    selected_machines: "{{ machines + vulnerables.machines }}"
  ansible.builtin.include_tasks: external/external_firewall.yml
  when: is_edge_router
