# Change Domain Controller Hostname to DC01

- name: Change the hostname to DC01
  ansible.windows.win_hostname:
    name: DC01
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

# Set Static address to DC

# - name: Set static IP address
#   win_shell: "(new-netipaddress -InterfaceAlias Ethernet -IPAddress 192.168.121.155 -prefixlength 24 -defaultgateway 192.168.121.1)"
#   ignore_errors: True

# - name: Set up static IP address
#   win_shell: "Get-NetIpAddress -InterfaceAlias 'Ethernet' | New-NetIpAddress -IpAddress 192.168.121.155 -PrefixLength 24 -DefaultGateway 192.168.121.1"
#   async: 100 # Using "fire-and-forget" asynchronous execution for this task, otherwise it will always fail and timeout
#   poll: 0

# - name: Wait for the hosts network interface to come back up
#   local_action:
#     module: wait_for
#     host: "{{ ansible_host }}"
#     port: 5985
#     delay: 10
#     state: started
#   register: wait_result

# - name: Set a single address on the adapter named Ethernet
#   ansible.windows.win_dns_client:
#     adapter_names: Ethernet
#     dns_servers: 192.168.121.155

- name: Install Active Directory
  win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
  register: result

- name: Create Domain
  win_domain: >
      dns_domain_name='xyz.com'
      safe_mode_password='notAComplexPassw0rd!'
  register: ad

- name: Reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed

- name: Set internal DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Create reverse DNS zone
  win_shell: "Add-DnsServerPrimaryZone -NetworkID 192.168.121.0/24 -ReplicationScope Forest"
  retries: 30
  delay: 60
  register: result           
  until: result is succeeded
