# Change Domain Controller Hostname to DC01

- name: Change the hostname to DC01
  ansible.windows.win_hostname:
    name: DC01
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: Install Active Directory
  ansible.windows.win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
  register: result

- name: Create Domain
  ansible.windows.win_domain: >
      dns_domain_name='xyz.com'
      safe_mode_password='notAComplexPassw0rd!'
  register: ad

- name: Reboot server
  ansible.windows.win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed

- name: Set internal DNS server
  ansible.windows.win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Create reverse DNS zone
  ansible.windows.win_shell: "Add-DnsServerPrimaryZone -NetworkID 192.168.121.0/24 -ReplicationScope Forest"
  retries: 30
  delay: 60
  register: result           
  until: result is succeeded

# Add Network Share

- name: Add Private Share
  ansible.windows.win_share:
    name: internal
    description: Top-Secret Share
    path: C:\Users\Administrator
    list: true
    full: xyz\Domain Admins
    # deny: xyz\Domain Users

# Copy AD files into Win Server

- name: Copy Scenario Files
  ansible.windows.win_copy:
    src: ad/code
    dest: C:\Users\Administrator

- name: Copy Flag to Private Share
  ansible.windows.win_copy:
    src: ad/flag.txt
    dest: C:\Users\Administrator\flag.txt

# PS Scripts

- name: Allow Remote Desktop
  ansible.windows.win_shell: .\allow_rdp.ps1
  args:
    chdir: C:\\Users\\Administrator\\code

- name: Change Admin accounts' Credentials
  ansible.windows.win_shell: .\change_admin_creds.ps1
  args:
    chdir: C:\\Users\\Administrator\\code

- name: Generate Random Vulnerable AD Schema
  ansible.windows.win_shell: .\random_domain.ps1 .\ad_schema.json -UserCount 12 -GroupCount 4 -LocalAdminCount 1
  args:
    chdir: C:\\Users\\Administrator\\code

- name: Generate Vulnerable AD Configuration
  ansible.windows.win_shell: .\gen_ad.ps1 .\ad_schema.json
  args:
    chdir: C:\\Users\\Administrator\\code

- name: Remove Code Directory
  ansible.windows.win_file:
    path: C:\Users\Administrator\code
    state: absent
