- name: Create new user
  tags: always
  user:
    name: simone
    groups: root
    password: '*' # https://github.com/relrod/ansible/commit/859726eaab17c735bd5106bdce6c662504168382

- name: Add SSH key for user
  tags: always
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILuxBPBtQPNCgp3DdxsqKD3RaJ7wVBqPjBRne329kHyU Thesis_Containers"

- name: Add sudoers file for user
  tags: always
  copy:
    src: files/sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440

- name: generate sshd_config file from a template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh